# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-28 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=None, upload_to='users_image', verbose_name='图片'),
        ),
    ]
